### ISSUE TITLE
restricted to element

### ISSUE THREAD

**Issue by joshualinog** [2013gang/angular-video-background#2]
Is there any fundamental reason the directive is restricted to an element? If so, it would be helpful to me if you could give me the rationale. If not, it makes the adoption a tad more tedious if there is already css in place that expects an element AND it can make older versions of IE hiccup.

**Comment by joshualinog** [comment]
as an update, there were no readily apparent breaking changes associated with giving the "restrict" property of the directive configuration the value of "EA" {restrict: 'EA'..}

**Comment by joshualinog** [comment]
hey guys, additionally, and i think, SLIGHTLY, related (if my first suggestion is related to adoptability): i added the property of transclude: true, and added the line '<div ng-transclude></div>'+ to the template. In my use case, I was putting the vid-bg directive as an attribute on a parent element that had several child elements. Your template was overriding this dom content because directives do not transclude by default.

**Comment by 2013gang** [comment]
Hi @jajourda sorry for late reply, i am just back from a long vacation.

There is no fundamental reason that this directive is restricted to element, it is just my personal preference. If you want to style it, css can be applied to any tag (html element).

If you want to add the directive to a parent element, i think you can just add the directive as One child of it, instead of applying it to the whole parent element. And also if the parent element is not "full screen", you can set the attribute full-screen to false.

if the above suggestion does not  work for you, I will try to play with it in a couple of days. Thanks!

**Comment by 2013gang** [comment]
Hi @jajourda,

For directive restriction, we can totally make it to 'AEC', but styling on custom html tag should also be good. I am not sure what you mean by 

> AND it can make older versions of IE hiccup.

can you explain further?

For the idea of using transfusion, i can think we can avoid it at least for your use case. We can use attribute `fullScreen` to make the video only cover your parent element's background.

Thanks!

**Comment by joshualinog** [comment]
haven't tried this yet. will let you know. kind of in the thick of it now, so rather than keep this open, i will take your word and close it. i think i made some assumptions without thoroughly understanding your underlying code.
